[package]
name = "node-testing"
version = "3.0.0-dev"
authors = ["Axia Technologies <admin@axiacoin.network>"]
description = "Test utilities for Axlib node."
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://axlib.io"
repository = "https://github.com/axiatech/axlib/"
publish = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sc-service = { version = "0.10.0-dev", features = [
    "test-helpers",
    "db",
], path = "../../../client/service" }
sc-client-db = { version = "0.10.0-dev", path = "../../../client/db/", features = [
    "kvdb-rocksdb",
    "parity-db",
] }
sc-client-api = { version = "4.0.0-dev", path = "../../../client/api/" }
sc-consensus = { version = "0.10.0-dev", path = "../../../client/consensus/common" }
codec = { package = "parity-scale-codec", version = "2.0.0" }
sp-keyring = { version = "5.0.0", path = "../../../primitives/keyring" }
node-executor = { version = "3.0.0-dev", path = "../executor" }
node-primitives = { version = "2.0.0", path = "../primitives" }
node-runtime = { version = "3.0.0-dev", path = "../runtime" }
sp-core = { version = "5.0.0", path = "../../../primitives/core" }
sp-io = { version = "5.0.0", path = "../../../primitives/io" }
sp-runtime = { version = "5.0.0", path = "../../../primitives/runtime" }
sc-executor = { version = "0.10.0-dev", path = "../../../client/executor", features = [
    "wasmtime",
] }
sp-consensus = { version = "0.10.0-dev", path = "../../../primitives/consensus/common" }
frame-system = { version = "4.0.0-dev", path = "../../../frame/system" }
axlib-test-client = { version = "2.0.0", path = "../../../test-utils/client" }
pallet-transaction-payment = { version = "4.0.0-dev", path = "../../../frame/transaction-payment" }
pallet-asset-tx-payment = { version = "4.0.0-dev", path = "../../../frame/transaction-payment/asset-tx-payment/" }
sp-api = { version = "4.0.0-dev", path = "../../../primitives/api" }
sp-timestamp = { version = "4.0.0-dev", default-features = false, path = "../../../primitives/timestamp" }
sp-block-builder = { version = "4.0.0-dev", path = "../../../primitives/block-builder" }
sc-block-builder = { version = "0.10.0-dev", path = "../../../client/block-builder" }
sp-inherents = { version = "4.0.0-dev", path = "../../../primitives/inherents" }
sp-blockchain = { version = "4.0.0-dev", path = "../../../primitives/blockchain" }
log = "0.4.8"
tempfile = "3.1.0"
fs_extra = "1"
futures = "0.3.1"
