[package]
name = "axlib-frame-rpc-support"
version = "3.0.0"
authors = [
    "Axia Technologies <admin@axiacoin.network>",
    "Andrew Dirksen <andrew@dirksen.com>",
]
edition = "2021"
license = "Apache-2.0"
homepage = "https://axlib.io"
repository = "https://github.com/axiatech/axlib/"
description = "Axlib RPC for FRAME's support"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
futures = "0.3.16"
jsonrpc-client-transports = { version = "18.0.0", features = ["http"] }
codec = { package = "parity-scale-codec", version = "2.0.0" }
serde = "1"
frame-support = { version = "4.0.0-dev", path = "../../../../frame/support" }
sp-storage = { version = "5.0.0", path = "../../../../primitives/storage" }
sc-rpc-api = { version = "0.10.0-dev", path = "../../../../client/rpc-api" }

[dev-dependencies]
frame-system = { version = "4.0.0-dev", path = "../../../../frame/system" }
scale-info = "1.0"
tokio = "1.15"
