[package]
name = "node-runtime-generate-bags"
version = "3.0.0"
authors = ["Axia Technologies <admin@axiacoin.network>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://axlib.io"
repository = "https://github.com/axiatech/axlib/"
description = "Bag threshold generation script for pallet-bag-list and node-runtime."
readme = "README.md"

[dependencies]
node-runtime = { version = "3.0.0-dev", path = "../../../../bin/node/runtime" }
generate-bags = { version = "4.0.0-dev", path = "../" }

# third-party
clap = { version = "3.0", features = ["derive"] }
